# CNN

## Regression

单通道

In [10]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler #only can be imported above pytorch0.2.0

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.pool0 = nn.AvgPool2d((2, 4), padding=1)
        self.conv1 = nn.Conv2d(1, 5, 4)
        self.pool1 = nn.AvgPool2d(3)
        self.conv2 = nn.Conv2d(5, 5, 3)
        self.pool2 = nn.MaxPool2d(3)
        self.fc1 = nn.Linear(80, 1)
        
    def forward(self, x):
        x = self.pool0(x)
        x = self.pool1(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = x.view(-1, 5*4*4)
        x = self.fc1(x)
        return x

net = Net()
criterion = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.01)

In [28]:
import netCDF4  # netCDF4非Python自带包，需要自行下载

import numpy as np

f = netCDF4.Dataset('D:\\sst.mnmean.nc')  # ftp://ftp.cdc.noaa.gov/Datasets/noaa.ersst.v5/sst.mnmean.nc
SST = f.variables['sst'][-1203:, :, :].data

SST[SST < -2] = 0

In [29]:
month_mean = np.zeros((12, 89, 180))
month_s = np.arange(0, 1188, 12)
for i in range(12):
    month_mean[i] = np.average(SST[month_s + i], axis = 0)
    SST[month_s + i] -= month_mean[i]
for i in range(12):
    SST[1188 + i] -= month_mean[i]
for i in range(3):
    SST[1200 + i] -= month_mean[i]

In [8]:
SST = SST.reshape((1200, 1, 89, 180))

X_train = SST[:-16]
X_train = torch.from_numpy(X_train)
X_valid = SST[-16:-4]
X_valid = torch.from_numpy(X_valid)

In [6]:
loc = ((134, 44), \
       (94, 44), \
       (57, 37), \
       (39, 44), \
       (21, 36), \
       (9, 16), \
       (172, 59), \
       (158, 28), \
       (65, 64), \
       (0, 10))

In [11]:
for row in loc:
    y_train = SST[1:-15, :, row[1], row[0]]
    y_train = torch.from_numpy(y_train)
    y_valid = SST[-15:-3, :, row[1], row[0]]
    y_valid = torch.from_numpy(y_valid)

    for epoch in range(500):  # loop over the dataset multiple times
        optimizer.zero_grad()
        outputs = net(X_train)
        loss = criterion(outputs, y_train)
        loss.backward()
        optimizer.step()

        outputs_valid = net(X_valid)
        loss_valid = criterion(outputs_valid, y_valid)
        print(epoch, loss.item(), loss_valid.item())

    break

0 1.0465993881225586 0.6835797429084778
1 0.9747850298881531 0.6549382209777832
2 0.8863504528999329 0.6098104119300842
3 0.7840589284896851 0.5596358180046082
4 0.6766080260276794 0.5468974709510803
5 0.5807129144668579 0.7936881184577942
6 0.5363522171974182 1.088138222694397
7 0.5773686766624451 0.8834357261657715
8 0.615320086479187 0.9258086085319519
9 0.5854175686836243 0.7049086093902588
......
490 0.13504692912101746 0.2542419135570526
491 0.13465538620948792 0.2536483705043793
492 0.134561225771904 0.2488059401512146
493 0.13465766608715057 0.25551173090934753
494 0.13477489352226257 0.246018648147583
495 0.13469943404197693 0.2529502809047699
496 0.13452135026454926 0.24460838735103607
497 0.13427981734275818 0.24881041049957275
498 0.13404397666454315 0.2467304915189743
499 0.1338791698217392 0.2460906058549881


预测（92°W，0°）今年3月份海温（真实值为27.26599℃）

In [30]:
X_test = SST[-2].reshape((1, 1, 89, 180))
X_test = torch.from_numpy(X_test)

y_fore = net(X_test) + month_mean[2, row[1], row[0]]
y_fore

tensor([[ 26.5089]])

双通道

In [29]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler #only can be imported above pytorch0.2.0

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.pool0 = nn.AvgPool2d((2, 4), padding=1)
        self.conv1 = nn.Conv2d(2, 5, 4)
        self.pool1 = nn.AvgPool2d(3)
        self.conv2 = nn.Conv2d(5, 5, 3)
        self.pool2 = nn.AvgPool2d(3)
        self.fc1 = nn.Linear(80, 1)
        
    def forward(self, x):
        x = self.pool0(x)
        x = self.pool1(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = x.view(-1, 5*4*4)
        x = self.fc1(x)
        return x

In [16]:
import netCDF4  # netCDF4非Python自带包，需要自行下载

import numpy as np

f = netCDF4.Dataset('D:\\sst.mnmean.nc')  # ftp://ftp.cdc.noaa.gov/Datasets/noaa.ersst.v5/sst.mnmean.nc
SST = f.variables['sst'][-1203:, :, :].data

SST[SST < -2] = 0

In [17]:
month_mean = np.zeros((12, 89, 180))
month_s = np.arange(0, 1188, 12)
for i in range(12):
    month_mean[i] = np.average(SST[month_s + i], axis = 0)
    SST[month_s + i] -= month_mean[i]
for i in range(12):
    SST[1188 + i] -= month_mean[i]
for i in range(3):
    SST[1200 + i] -= month_mean[i]

In [18]:
SST = SST.reshape((1203, 1, 89, 180))

X_train = np.zeros((1186, 2, 89, 180), dtype=np.float32)
X_train[:, 0] = SST[:-17, 0]
X_train[:, 1] = SST[1:-16, 0]
X_train = torch.from_numpy(X_train)

X_valid = np.zeros((12, 2, 89, 180), dtype=np.float32)
X_valid[:, 0] = SST[-17:-5, 0]
X_valid[:, 1] = SST[-16:-4, 0]
X_valid = torch.from_numpy(X_valid)

In [19]:
loc = ((134, 44), \
       (94, 44), \
       (57, 37), \
       (39, 44), \
       (21, 36), \
       (9, 16), \
       (172, 59), \
       (158, 28), \
       (65, 64), \
       (0, 10))

In [33]:
for row in loc:
    y_train = SST[2:-15, :, row[1], row[0]]
    y_train = torch.from_numpy(y_train)
    y_valid = SST[-15:-3, :, row[1], row[0]]
    y_valid = torch.from_numpy(y_valid)
    
    net = Net()
    criterion = nn.MSELoss()
    optimizer = optim.Adam(net.parameters(), lr=0.01)

    for epoch in range(500):  # loop over the dataset multiple times
        optimizer.zero_grad()
        outputs = net(X_train)
        loss = criterion(outputs, y_train)
        loss.backward()
        optimizer.step()

        outputs_valid = net(X_valid)
        loss_valid = criterion(outputs_valid, y_valid)
        print(epoch, loss.item(), loss_valid.item())

    break

0 1.0924222469329834 0.7783412933349609
1 1.0704162120819092 0.7477688789367676
2 1.0477246046066284 0.7139258980751038
3 1.017866849899292 0.689863920211792
4 0.9753577709197998 0.7009252905845642
5 0.9219707250595093 0.7884209156036377
6 0.8792669177055359 0.9841131567955017
7 0.8626843690872192 1.0334067344665527
8 0.8389838337898254 0.8623300194740295
9 0.7954409718513489 0.656138002872467
......
490 0.14715714752674103 0.14399534463882446
491 0.14776194095611572 0.14386199414730072
492 0.15010632574558258 0.15215153992176056
493 0.15140803158283234 0.14585167169570923
494 0.15049022436141968 0.14933845400810242
495 0.14814625680446625 0.14477448165416718
496 0.1465679109096527 0.14365209639072418
497 0.14680719375610352 0.1474066525697708
498 0.14811305701732635 0.14321763813495636
499 0.14914001524448395 0.14752419292926788


查看参数

In [45]:
params = net.state_dict()
for key, value in params.items():
    print(key)
    print(value)

conv1.weight
tensor([[[[ 0.1510, -0.1077, -0.0834,  0.0309],
          [-0.0083, -0.0001, -0.1092,  0.1961],
          [-0.1258, -0.0724,  0.0615,  0.2049],
          [-0.2861, -0.2778, -0.0905,  0.0435]],

         [[ 0.2954,  0.3766,  0.2090,  0.3081],
          [ 0.2486,  0.3672,  0.3810,  0.5710],
          [-0.2887,  0.1020,  0.2948,  0.5198],
          [-0.3312,  0.2737,  0.4264,  0.2467]]],


        [[[ 0.4285,  0.3927,  0.4240,  0.3062],
          [ 0.2997,  0.3778,  0.2909,  0.1247],
          [ 0.1028, -0.0430, -0.0430, -0.0094],
          [ 0.1991, -0.1548, -0.1521, -0.2047]],

         [[-0.3585, -0.3561,  0.0138, -0.1086],
          [ 0.0507, -0.1134, -0.1795,  0.0252],
          [ 0.1738,  0.0330, -0.1451, -0.1173],
          [ 0.1612, -0.1298, -0.3141, -0.5173]]],


        [[[-0.1371, -0.0787, -0.1715, -0.0309],
          [ 0.0039, -0.1633,  0.0560, -0.0061],
          [-0.1149, -0.2434, -0.0266,  0.1660],
          [-0.3392, -0.1659,  0.0258,  0.3732]],

         [[ 0

In [50]:
params['fc1.bias'].numpy()

array([-0.29721215], dtype=float32)

In [64]:
X_test

tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]]])

In [71]:
mat = net.pool0(X_test)
mat

tensor([[[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.5791,  1.1537,  1.0077,  ..., -0.0000, -0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.6774,  1.3424,  1.3536,  ..., -0.0000, -0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]]])

In [72]:
mat = net.pool1(F.relu(net.conv1(mat)))
mat

tensor([[[[ 2.9896,  2.7273,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
            0.0000,  0.0000,  0.0000,  0.0083,  0.0000,  0.0000,  0.3413],
          [ 3.0476,  4.1616,  0.6891,  0.0000,  0.0000,  0.0000,  0.5120,
            0.1046,  0.0506,  0.0256,  0.0559,  0.3914,  0.2587,  0.8099],
          [ 0.4298,  0.0136,  0.0000,  0.0000,  0.0000,  0.0177,  2.2565,
            3.5687,  2.2694,  0.0290,  0.0000,  0.6461,  0.4188,  0.5486],
          [ 0.2837,  0.1487,  0.0131,  0.0000,  1.3816,  1.3646,  0.9308,
            1.7003,  1.4421,  0.3033,  0.0007,  0.8213,  0.7713,  1.3598],
          [ 0.8529,  0.3343,  0.0017,  0.0275,  3.2024,  2.9152,  3.2534,
            1.6996,  0.0464,  0.7146,  0.3012,  2.0293,  1.7992,  1.7493],
          [ 0.1673,  0.7290,  0.0984,  0.5467,  2.5228,  2.6183,  1.9869,
            1.4354,  1.0777,  2.1503,  1.3492,  1.9878,  1.6343,  0.8734],
          [ 0.0161,  1.4348,  1.2058,  1.2815,  0.0603,  0.6792,  1.7345,
            2.1348,  1.8072,  1.

In [73]:
mat = net.pool2(F.relu(net.conv2(mat)))
mat

tensor([[[[ 1.7245,  2.9144,  2.0041,  1.7712],
          [ 2.3932,  1.3243,  2.3043,  1.8784],
          [ 1.4030,  2.8169,  1.7986,  2.3987],
          [ 1.6967,  1.3228,  1.4515,  2.0170]],

         [[ 2.6577,  1.0501,  1.6945,  1.1951],
          [ 0.7797,  1.7055,  0.6594,  0.9934],
          [ 1.5289,  0.6554,  1.5661,  1.0234],
          [ 1.6763,  1.5860,  1.6955,  1.1643]],

         [[ 0.3246,  0.6026,  0.1709,  0.3178],
          [ 0.4125,  0.6620,  0.0015,  0.2274],
          [ 0.4246,  0.6517,  0.1932,  0.7214],
          [ 0.2037,  0.8563,  0.1220,  0.2548]],

         [[ 0.4498,  0.6473,  0.6233,  0.2590],
          [ 0.4052,  1.1604,  0.7552,  1.0241],
          [ 1.0047,  0.7187,  1.1670,  1.3284],
          [ 0.9126,  0.9888,  0.5209,  0.2752]],

         [[ 0.1560,  0.6472,  0.0675,  0.3956],
          [ 0.5628,  0.0311,  0.0000,  0.0269],
          [ 0.0000,  0.5598,  0.0000,  0.0000],
          [ 0.0566,  0.2672,  0.0352,  0.5312]]]])

In [74]:
mat = mat.view(-1, 80)
mat

tensor([[ 1.7245,  2.9144,  2.0041,  1.7712,  2.3932,  1.3243,  2.3043,
          1.8784,  1.4030,  2.8169,  1.7986,  2.3987,  1.6967,  1.3228,
          1.4515,  2.0170,  2.6577,  1.0501,  1.6945,  1.1951,  0.7797,
          1.7055,  0.6594,  0.9934,  1.5289,  0.6554,  1.5661,  1.0234,
          1.6763,  1.5860,  1.6955,  1.1643,  0.3246,  0.6026,  0.1709,
          0.3178,  0.4125,  0.6620,  0.0015,  0.2274,  0.4246,  0.6517,
          0.1932,  0.7214,  0.2037,  0.8563,  0.1220,  0.2548,  0.4498,
          0.6473,  0.6233,  0.2590,  0.4052,  1.1604,  0.7552,  1.0241,
          1.0047,  0.7187,  1.1670,  1.3284,  0.9126,  0.9888,  0.5209,
          0.2752,  0.1560,  0.6472,  0.0675,  0.3956,  0.5628,  0.0311,
          0.0000,  0.0269,  0.0000,  0.5598,  0.0000,  0.0000,  0.0566,
          0.2672,  0.0352,  0.5312]])

In [75]:
mat = net.fc1(mat)
mat

tensor([[ 0.5504]])

In [76]:
mat + month_mean[2, row[1], row[0]]

tensor([[ 27.2570]])

预测（92°W，0°）今年3月份海温（真实值为27.26599℃）

In [31]:
X_test = np.zeros((1, 2, 89, 180), dtype=np.float32)
X_test[0, 0] = SST[-3, 0]
X_test[0, 1] = SST[-2, 0]
X_test = torch.from_numpy(X_test)

y_fore = net(X_test) + month_mean[2, row[1], row[0]]
y_fore

tensor([[ 27.5039]])

In [32]:
for row in loc:
    y_train = SST[2:-15, :, row[1], row[0]]
    y_train = torch.from_numpy(y_train)
    y_valid = SST[-15:-3, :, row[1], row[0]]
    y_valid = torch.from_numpy(y_valid)
    
    net = Net()
    criterion = nn.MSELoss()
    optimizer = optim.Adam(net.parameters(), lr=0.01)

    for epoch in range(1000):  # loop over the dataset multiple times
        optimizer.zero_grad()
        outputs = net(X_train)
        loss = criterion(outputs, y_train)
        loss.backward()
        optimizer.step()

        outputs_valid = net(X_valid)
        loss_valid = criterion(outputs_valid, y_valid)
    
    print(net(X_test) + month_mean[2, row[1], row[0]])

tensor([[ 27.5720]])
tensor([[ 29.1317]])
tensor([[ 27.6299]])
tensor([[ 29.9275]])
tensor([[ 27.4515]])
tensor([[ 3.9730]])
tensor([[ 24.6470]])
tensor([[ 19.6922]])
tensor([[ 16.1494]])
tensor([[ 5.9008]])


## Classfication

数据上传到百度网盘 内涝等级识别 文件夹

In [8]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler #only can be imported above pytorch0.2.0
from torchvision import datasets, models, transforms
import os
import numpy as np

In [ ]:
data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])

image_datasets = datasets.ImageFolder('train',
                                      data_transforms)

test_datasets = datasets.ImageFolder('test',
                                      data_transforms)

In [ ]:
def make_weights_for_balanced_classes(images, nclasses):                        
    count = [0] * nclasses
    for item in images:
        count[item[1]] += 1
    weight_per_class = [0.] * nclasses
    N = float(sum(count))
    for i in range(nclasses):
        weight_per_class[i] = N/float(count[i])
    weight = [0] * len(images)
    for idx, val in enumerate(images):
        weight[idx] = weight_per_class[val[1]]
    return weight

weight = make_weights_for_balanced_classes(image_datasets, 5)

sampler = torch.utils.data.sampler.WeightedRandomSampler(weight, len(weight))

dataloders = torch.utils.data.DataLoader(image_datasets,
                                         batch_size=1,
                                         sampler = sampler,
                                         num_workers=0)

datatest = torch.utils.data.DataLoader(test_datasets,
                                         batch_size=1,
                                         shuffle=True,
                                         num_workers=0)

In [ ]:
net = models.resnet18(pretrained=True)
num_ftrs = net.fc.in_features
net.fc = nn.Linear(num_ftrs, 5)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
scheduler = lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

In [ ]:
for epoch in range(25):  # loop over the dataset multiple times
    scheduler.step()
    i = 0
    loss_sum = 0
    for data in dataloders:
        inputs, labels = data
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss_sum += loss.item()
        loss.backward()
        optimizer.step()

        i += 1

        if i % 1000 == 0:

            print(i, loss_sum / 1000)

            loss_sum = 0

    correct = np.zeros((5, 5))
    for data in datatest:
        inputs, labels = data
        outputs = net(inputs)
        _, predicted = torch.max(outputs.data, 1)
        correct[int(labels), int(predicted)] += 1
    for row in correct:
        print(row)

In [ ]:
torch.save(net.state_dict(), 'test.pkl')

预测

In [14]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler #only can be imported above pytorch0.2.0
from torchvision import datasets, models, transforms
import os
import numpy as np

data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])

test_datasets = datasets.ImageFolder('test_new',
                                      data_transforms)

datatest = torch.utils.data.DataLoader(test_datasets,
                                         batch_size=1,
                                         shuffle=True,
                                         num_workers=0)

net = models.resnet18(pretrained=True)
num_ftrs = net.fc.in_features
net.fc = nn.Linear(num_ftrs, 5)

net.load_state_dict(torch.load('test.pkl'), strict=False)

for data in datatest:
    inputs, labels = data
    outputs = F.softmax(net(inputs))
    print(outputs.detach().numpy()[0], int(labels))

d:\python36\lib\site-packages\ipykernel_launcher.py:33: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


[6.1513543e-05 9.9989283e-01 4.3832726e-05 1.4410913e-06 3.7497728e-07] 1
[1.9392589e-06 9.7590164e-06 1.0727131e-05 1.8801609e-04 9.9978954e-01] 4
[1.6476604e-05 3.4625569e-04 9.9959826e-01 3.7069316e-05 1.9144195e-06] 2
[1.8656605e-05 2.6466485e-04 2.7656858e-04 4.3591481e-01 5.6352532e-01] 3
[9.9962622e-01 3.5922590e-04 7.4621644e-06 5.9296272e-06 1.1686778e-06] 0
