#Python是一种动态的、面向对象的脚本语言

动态：变量使用之前不需要类型声明； 

面向对象：以对象作为基本程序结构单位，语言中提供了类、继承等成分；

脚本：以文本保存，只在被调用时进行解释。

Python目前有两个主流版本：Python 2和Python 3。
    
推荐使用Python3，因为Python 2将于2020年将停止更新，很多库也停止对Python 2的更新。

Python的安装有多种方式，可以用[Anaconda](https://www.anaconda.com/)安装，也可使用[Python](https://www.python.org/)官网提供的安装包安装。

Python安装完毕后最好检查一下Python和pip的环境变量。

pip是Python很重要的一个模块Python 包管理工具，提供了对Python 包的查找、下载、安装、卸载的功能。

关于Python的基础教程参考https://docs.python.org/3.6/tutorial/introduction.html

In [1]:
17 / 3  # 与大多数编程语言不同，在Python 3中，两个整数型相除结果为浮点型。

5.666666666666667

In [2]:
17 // 3  # floor division discards the fractional part

5

In [3]:
17 % 3  # the % operator returns the remainder of the division

2

In [4]:
17 ** 3 # 也可以使用pow(17, 3)，但不能使用17^3

4913

Python没有char这个变量，只有str。单双引号都可以使用，但要注意细节。字符串前加r避免转义。

In [14]:
'doesn\'t'  # use \' to escape the single quote...

"doesn't"

In [15]:
"doesn't"  # ...or use double quotes instead

"doesn't"

In [16]:
print('C:\some\name')  # here \n means newline!

C:\some
ame


In [17]:
print(r'C:\some\name')  # note the r before the quote

C:\some\name


In [19]:
word = 'Python'
word[0]  # character in position 0

'P'

In [22]:
word[5]  # character in position 5

'n'

In [21]:
word[0:2]  # characters from position 0 (included) to 2 (excluded)

'Py'

In [23]:
word[2:5]  # characters from position 2 (included) to 5 (excluded)

'tho'

In [24]:
word[:2]   # character from the beginning to position 2 (excluded)

'Py'

In [25]:
word[4:]   # characters from position 4 (included) to the end

'on'

In [26]:
word[-2:]  # characters from the second-last (included) to the end

'on'

对于Python的数值变量和字符串变量，赋值不存在传地址不传值的情况

In [27]:
a = 1
b = a
b

1

In [28]:
a += 1  # a += 1 等效于 a = a + 1，Python中没有a ++这种形式
a

2

In [29]:
b  # b的值没有随a的值发生变化

1

In [30]:
a = 'Python'
b = a
b

'Python'

In [31]:
a += '!'
a

'Python!'

In [32]:
b  #b的值没有随a的值发生变化

'Python'

Python中常用的表示一组数据的变量有tuple（元组）、list（列表）、set（集合）、dict（字典）

tuple不允许赋值后再对某个元素进行赋值，常用来存储程序中的固定参数

In [9]:
a = (1, 2, 3)  # tuple的赋值为小括号
a[0] = 2

TypeError: 'tuple' object does not support item assignment

In [5]:
a = (1)
a

1

In [8]:
a = (1,)  # 只有一个元素时需要加,
a

(1,)

set中不允许存在重复的元素，常用来快速地统计一组数据中有几个不重复的值

In [10]:
a = {1, 2, 3, 3}   # set的赋值为大括号
a

{1, 2, 3}

In [11]:
a[0]  # set是无序的，不存在索引

TypeError: 'set' object does not support indexing

列表是比较常用的存储一系列数据的变量

In [12]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [13]:
squares[0]  # indexing returns the item

1

In [14]:
squares[-1]

25

In [15]:
squares[-3:]  # slicing returns a new list

[9, 16, 25]

In [16]:
squares[:] # 列表的索引和字符串一样

[1, 4, 9, 16, 25]

当a是列表时，用把a赋值给x，a的值发生变化，x也变

In [17]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x

[['a', 'b', 'c'], [1, 2, 3]]

In [18]:
x[0]

['a', 'b', 'c']

In [19]:
x[0][1]

'b'

In [20]:
a += ['d']
a

['a', 'b', 'c', 'd']

In [21]:
x

[['a', 'b', 'c', 'd'], [1, 2, 3]]

字典的索引可以不为自然数，在某些情况下应用比较方便

In [26]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127  # 若key存在则改变key的值，若不存在则直接创建新的key和value
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [27]:
tel['jack']

4098

In [28]:
tel.keys()

dict_keys(['jack', 'sape', 'guido'])

可以使用集合快速求一个元组/列表/字典中不重复的值

In [29]:
a = [1, 1, 1, 2, 3]
a = list(set(a))
a

[1, 2, 3]

元组、集合、列表、字典、字符串的互相转化、裁剪，以及元素的查找、替换、删除在之后的应用中自己探索。

In [30]:
a = [1, '1', (1,), {1}]
for row in a:
	if type(row) == int:
		print(row, 'find int!')
	elif type(row) == str:
		print(row, 'find str!')
	else:
		pass

1 find int!
1 find str!


In [31]:
for i in range(4):
	print(i)

0
1
2
3


In [39]:
i = 0
while i < 10:
	i += 1
i

10

In [33]:
i = 0
while i < 4:
	i += 1
	if i == 3:
		break  # break跳出循环
	print(i)

1
2


In [34]:
i = 0
while i < 4:
	i += 1
	if i == 3:
		continue  # countiue结束当前循环进入下一个循环，故i等于3时没有被print出来
	print(i)

1
2
4


In [35]:
for i in range(3):
	i_break = 0  # break只能跳出一层循环，跳出多层循环需要加个辅助变量（或者使用return，return涉及到函数，暂时不讲，可以自己查阅相关方法）
	for j in range(3):
		print(i, j)
		if i + j >= 2:
			i_break = 1
			break
	if i_break == 1:
		break

0 0
0 1
0 2


In [37]:
i = 0
while 1:  # 谨慎使用while，可能陷入死循环
	if i >= 4:
		break
	print(i)
	#i += 1  # 请在自己确保能够中断程序的情况下注释掉并运行此代码

0
1
2
3


NumPy系统是Python的一种开源的数值计算扩展包。

Numpy内置了并行运算功能，当系统有多个核心时，做某种计算时，Numpy会自动做并行计算。

Numpy底层使用C语言编写，其对数组的操作速度不受python解释器的限制，大幅提升计算效率。

关于Numpy的基础教程参考https://docs.scipy.org/doc/numpy/user/quickstart.html

In [40]:
import numpy as np  # 一定要import
a = np.arange(15).reshape(3, 5)  # array（数组）是numpy的一个基本变量之一
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
a.shape

(3, 5)

In [42]:
a.ndim

2

In [43]:
a.dtype.name

'int32'

In [44]:
a.size

15

In [45]:
type(a)

numpy.ndarray

In [46]:
a = np.array([2,3,4])
a.dtype

dtype('int32')

In [48]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [49]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [50]:
np.zeros( (3,4) )  # 建立3*4值为0的数组，注意数值类型是浮点数

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.ones( (2,3,4), dtype=np.int16 )  # 建立2*3*4的数值类型为int16，值为1的数组

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [52]:
np.arange( 10, 30, 5 )  # 以5为间隔，不含尾

array([10, 15, 20, 25])

In [53]:
np.arange(6)  #0到6，以1为间隔，不含尾

array([0, 1, 2, 3, 4, 5])

In [54]:
np.arange(4,6)  #4到6，以1为间隔，不含尾

array([4, 5])

In [55]:
np.arange( 0, 2, 0.3 )  #0到2，0.3为间隔，不含尾

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [56]:
np.linspace( 0, 2, 9 )  # 0到2，分成9份，含首尾，间隔为（2-0）/（9-1）

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [57]:
np.linspace( 2, 0, 9 )  # 2到0，分成9份，含首尾，间隔为（0-2）/（9-1）

array([2.  , 1.75, 1.5 , 1.25, 1.  , 0.75, 0.5 , 0.25, 0.  ])

当a是数组时，把a赋值给b只赋值了地址，赋值值应该用copy()

In [58]:
a = np.arange(0,6)
b = a
a += 1
a

array([1, 2, 3, 4, 5, 6])

In [59]:
b  # b随a的变化而变化

array([1, 2, 3, 4, 5, 6])

In [60]:
b = np.copy(a)
a += 1
a

array([2, 3, 4, 5, 6, 7])

In [61]:
b  # b不随a变化

array([1, 2, 3, 4, 5, 6])

In [62]:
a = np.random.random((2,3))  # 随机生成一个元素值为0到1之间的2*3的数组
a

array([[0.83914423, 0.72064884, 0.61617498],
       [0.12506563, 0.54233144, 0.09720195]])

In [63]:
a.sum()  # a的全部元素求和

2.940567061715948

In [64]:
a.mean()  # a的全部元素求均值

0.4900945102859913

In [65]:
a.min()  # a的全部元素求最小值

0.09720195039732327

In [66]:
a.max()  # a的全部元素求最大值

0.8391442254918468

In [67]:
a.std()  # a的全部元素的标准差，注意此处标准差除的是a的元素的个数，不是自由度，所以不是a的标准差的无偏估计

0.28320388125262574

In [68]:
a > 0.5  # 大于0.5的值为True（1），小于0.5的值为False（1），可用于快速设定示一变量

array([[ True,  True,  True],
       [False,  True, False]])

In [69]:
a[a > 0.5]  # 输出a大于0.5的全部元素

array([0.83914423, 0.72064884, 0.61617498, 0.54233144])

In [71]:
a[a > 0.5] = 1  # 将a中大于0.5的赋值为1
a

array([[1.        , 1.        , 1.        ],
       [0.12506563, 1.        , 0.09720195]])

In [82]:
# dir(a)  # 更多对于单个array处理的函数自己探索，dir()显示变量的属性和方法列表

In [83]:
# help(a)  # help()显示变量的帮助手册

一般情况下，array与array的计算都是元素与元素之间的计算

In [75]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a- b
c

array([20, 29, 38, 47])

In [76]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [77]:
10*np.sin(a)  # 类似函数还有cos()、log()、exp()等等……

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [78]:
a * b

array([  0,  30,  80, 150])

In [79]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
A * B  # 在array中，A * B表示对应元素相乘

array([[2, 0],
       [0, 4]])

In [80]:
A @ B  # @ 矩阵相乘

array([[5, 4],
       [3, 4]])

In [81]:
A.dot(B)  # 另一种矩阵相乘

array([[5, 4],
       [3, 4]])